fix: eliminate compile errors
dashevo/tenderdash pull request #238
Opened 2021-12-21 15:25 UTC by shotonoff

## Issue being fixed or feature implemented

## What was done?

Fixed most of the compile errors

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2021-12-22 06:22 UTC, QuantumExplorer requested changes

2021-12-22 06:22 UTC, QuantumExplorer commented on internal/consensus/reactor.go
>  			}
This logic will need to be changed, because if a node is lagging we should send the LastCommit, not the LastPrecommits.

2021-12-22 06:22 UTC, QuantumExplorer commented on internal/consensus/reactor.go
>  			}
And the last commit is a commit, not a vote in tenderdash

2021-12-22 06:22 UTC, QuantumExplorer commented on internal/consensus/reactor_test.go
> +	newValidatorTx1 := kvstore.MakeValSetChangeTx(newValidatorProTxHash1, &valPubKey1ABCI, testMinPower)
You can't just change 1 validator key in our system.

2021-12-22 06:22 UTC, QuantumExplorer commented on internal/consensus/types/peer_round_state.go
> -	prs.LastCommit = prs.LastCommit.Copy()
This should be LastPrecommits I think

2021-12-22 06:22 UTC, QuantumExplorer commented on privval/grpc/server_test.go
> +	valAddr := crypto.RandQuorumHash()
hahaha nope

2021-12-22 16:36 UTC, QuantumExplorer approved these changes

2021-12-24 09:55 UTC, QuantumExplorer requested changes

2021-12-24 09:55 UTC, QuantumExplorer commented on internal/consensus/peer_state.go
>  	Votes      int `json:"votes"`
We should add the Commit too

2021-12-24 09:55 UTC, QuantumExplorer commented on types/validator_set_test.go
> +	goodValSet, _ := factory.GenerateMockValidatorSet(4)
I think you might want RandomValidatorSet instead

2021-12-24 09:55 UTC, QuantumExplorer commented on types/vote_set_test.go
> +	valSet, mockPVs := factory.GenerateMockValidatorSet(numValidators)
You want RandomValidatorSet

2022-01-25 15:16 UTC, lklimek commented
To be merged using Squash feature

2022-01-26 10:00 UTC, merged