feat(consensus): add empty block on h-1 and h-2 apphash change
dashevo/tenderdash pull request #241
Opened 2021-12-28 11:26 UTC by lklimek

## Issue being fixed or feature implemented

Dash Drive needs additional (empty) block generated after AppHash change, so that we will have 2 blocks generated for each apphash change.

## What was done?

Modified needProofBlock to check apphash from block height-1 and height-2 when determining whether or not we should force new block creation.

## How Has This Been Tested?

## Breaking Changes

none

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2021-12-28 13:53 UTC, QuantumExplorer requested changes

2021-12-28 13:53 UTC, QuantumExplorer commented on consensus/state.go
> +	h1Equal := bytes.Equal(cs.state.AppHash, h1BlockMeta.Header.AppHash)
I would return immediately if h1 is not equal as there's no reason to load block at h-2.

2021-12-31 10:37 UTC, shumkov approved these changes
👍

2021-12-31 14:29 UTC, shotonoff approved these changes
🚀

2021-12-31 14:34 UTC, merged