fix: fix unit tests of backport v0.35
dashevo/tenderdash pull request #245
Opened 2022-01-10 13:27 UTC by shotonoff

## Issue being fixed or feature implemented
After fixing compile errors, now the codebase is ready to fix the unit tests after backporting v0.35

## What was done?
Fix unit tests for backport of v0.35

## How Has This Been Tested?
Run unit tests

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-01-13 16:24 UTC, lklimek requested changes
Please also run `make lint` and fix issues.

2022-01-13 16:24 UTC, lklimek commented on types/validator_set_test.go
> -func TestValSetUpdateOverflowRelated(t *testing.T) {
why is this test removed?

2022-01-13 16:24 UTC, lklimek commented on types/block_test.go
> -			"no signatures",
why is this test case removed?

2022-01-20 14:56 UTC, shotonoff reviewed
done

2022-01-25 15:03 UTC, lklimek approved these changes

2022-01-25 15:18 UTC, lklimek commented
Squash-merge

2022-02-09 08:26 UTC, merged